# Generated by Django 5.1.14 on 2025-12-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0017_remove_lazerwrapped_community_top_make_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LazerSession",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="session key",
                    ),
                ),
                ("session_data", models.TextField(verbose_name="session data")),
                ("expire_date", models.DateTimeField(db_index=True, verbose_name="expire date")),
            ],
            options={
                "db_table": "lazer_session",
            },
        ),
    ]
