# Generated by Django 5.1.15 on 2026-01-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lazer", "0018_lazersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationsubmission",
            name="plate_recognizer_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
