# Generated by Django 5.1.15 on 2026-01-18 14:48

from django.db import migrations, models

import lazer.models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0019_violationsubmission_plate_recognizer_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationreport",
            name="redacted_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=lazer.models.report_image_upload_to
            ),
        ),
    ]
