# Generated by Django 5.1.15 on 2026-02-17 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lazer", "0021_merge_0019_banner_0020_violationreport_redacted_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="violationreport",
            name="screenshot_after_submit",
        ),
        migrations.RemoveField(
            model_name="violationreport",
            name="screenshot_before_submit",
        ),
        migrations.RemoveField(
            model_name="violationreport",
            name="screenshot_error",
        ),
        migrations.RemoveField(
            model_name="violationreport",
            name="screenshot_final",
        ),
        migrations.RemoveField(
            model_name="violationreport",
            name="screenshot_success",
        ),
    ]
