# Generated by Django 4.2.11 on 2024-05-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_shirtinterest"),
    ]

    operations = [
        migrations.AddField(
            model_name="shirtinterest",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
