# Generated by Django 4.2.13 on 2024-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_shirtinterest_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="shirtinterest",
            name="fulfilled",
            field=models.BooleanField(default=False),
        ),
    ]
