# Generated by Django 4.2.13 on 2024-08-13 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_shirtinterest_fulfilled"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text="Your Philadelphia Street Address",
                max_length=256,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="council_district",
            field=models.IntegerField(
                choices=[
                    (0, "N/A - I do not live in Philadelphia"),
                    (1, "District 1"),
                    (2, "District 2"),
                    (3, "District 3"),
                    (4, "District 4"),
                    (5, "District 5"),
                    (6, "District 6"),
                    (7, "District 7"),
                    (8, "District 8"),
                    (9, "District 9"),
                    (10, "District 10"),
                ],
                verbose_name="Council District",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="newsletter_opt_in",
            field=models.BooleanField(default=False, verbose_name="Newsletter Opt-In"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid zipcode in formats 19107 or 19107-3200",
                        regex="^(^[0-9]{5}(?:-[0-9]{4})?$|^$)",
                    )
                ],
                verbose_name="Zip Code",
            ),
        ),
    ]
