# Generated by Django 4.2.13 on 2024-09-02 17:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_alter_profile_street_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
