# Generated by Django 4.2.13 on 2024-09-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="council_district",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "N/A - I do not live in Philadelphia"),
                    (1, "District 1"),
                    (2, "District 2"),
                    (3, "District 3"),
                    (4, "District 4"),
                    (5, "District 5"),
                    (6, "District 6"),
                    (7, "District 7"),
                    (8, "District 8"),
                    (9, "District 9"),
                    (10, "District 10"),
                ],
                null=True,
                verbose_name="Council District",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="newsletter_opt_in",
            field=models.BooleanField(
                default=False,
                help_text="Subscribe to Philly Bike Actions monthly newsletter.",
                verbose_name="Newsletter",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Your street address will be used to determine your Philadelphia "
                    "City Council District and connect you with actions "
                    "you can take in your specific neighborhood."
                ),
                max_length=256,
                null=True,
                verbose_name="Street Address",
            ),
        ),
    ]
