# Generated by Django 4.2.13 on 2024-12-27 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_alter_profile_street_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShirtInterest",
        ),
    ]
