# Generated by Django 4.2.13 on 2025-01-20 16:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0010_delete_shirtinterest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShirtOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid", models.BooleanField(default=False)),
                ("fulfilled", models.BooleanField(default=False)),
                ("billing_details", models.JSONField(blank=True, null=True)),
                ("shipping_details", models.JSONField(blank=True, null=True)),
                (
                    "fit",
                    models.IntegerField(
                        choices=[
                            (0, 'Unisex Classic Fit - "Go-To T-Shirt"'),
                            (1, "Women's Relaxed Fit - \"Women's Go-To Headliner Cropped Tee\""),
                        ]
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        choices=[(-2, "XS"), (-1, "S"), (0, "M"), (1, "L"), (2, "XL"), (3, "2XL")]
                    ),
                ),
                ("print_color", models.IntegerField(choices=[(0, "Pink"), (1, "Green")])),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tshirt_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
