# Generated by Django 4.2.13 on 2025-01-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_shirtorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shirtorder",
            name="fit",
            field=models.IntegerField(
                choices=[
                    (2, 'Unisex Classic Fit - "Next Level - Cotton T-Shirt - 3600"'),
                    (3, "Women's Relaxed Fit - \"Next Level - Women's Ideal Crop Top - 1580\""),
                ]
            ),
        ),
    ]
