# Generated by Django 4.2.13 on 2025-02-22 18:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_shirtorder_fit"),
    ]

    operations = [
        migrations.AddField(
            model_name="shirtorder",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="shirtorder",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("usps", "Usps"),
                    ("courier", "Courier"),
                    ("pickup", "Pickup"),
                    ("other", "Other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
