# Generated by Django 5.1.15 on 2026-02-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0022_profile_pronouns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(
                help_text="Select from recommendations, or type your own.",
                max_length=64,
                null=True,
                verbose_name="Pronouns",
            ),
        ),
    ]
