# Generated by Django 5.1.14 on 2025-11-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_scheduledevent_hidden"),
        ("facets", "0004_statehousedistrict_statesenatedistrict"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledevent",
            name="districts",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="facets.district"
            ),
        ),
        migrations.AddField(
            model_name="scheduledevent",
            name="registered_community_organizations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="+",
                to="facets.registeredcommunityorganization",
            ),
        ),
    ]
