# Generated by Django 4.2.13 on 2025-01-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplication",
            name="thread_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
