FROM node:22-bookworm AS lazer

WORKDIR /code/lazer_app/projectLazer/
COPY ./ /code/

RUN --mount=type=cache,target=/root/.npm,sharing=locked \
    npm install

RUN npx ionic build


FROM ghcr.io/astral-sh/uv:python3.13-trixie

RUN set -eux; \
    rm -f /etc/apt/apt.conf.d/docker-clean; \
    echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache;
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update \
    && apt-get install -y gettext binutils libproj-dev gdal-bin

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV UV_PROJECT_ENVIRONMENT=/home/user/.venv
ENV PATH="${PATH}:/home/user/.local/bin"

ARG USER_ID
ARG GROUP_ID
RUN groupadd -o -g $GROUP_ID -r usergrp
RUN useradd -o -m -u $USER_ID -g $GROUP_ID user
RUN mkdir /code
RUN chown user /code

USER user
WORKDIR /code
COPY pyproject.toml /code/pyproject.toml
COPY uv.lock /code/uv.lock
RUN --mount=type=cache,target=/home/user/.cache/uv,uid=$USER_ID,gid=$GROUP_ID \
    uv sync --group dev --group deploy

COPY . /code/
