# Generated by Django 4.2.13 on 2024-09-02 16:51

import uuid

import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        CreateExtension("postgis"),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("mpoly", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("properties", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredCommunityOrganization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("mpoly", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("properties", models.JSONField()),
            ],
        ),
    ]
