# Generated by Django 4.2.13 on 2024-09-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="targetable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="registeredcommunityorganization",
            name="targetable",
            field=models.BooleanField(default=False),
        ),
    ]
