# Generated by Django 5.1.14 on 2025-11-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facets", "0004_statehousedistrict_statesenatedistrict"),
        ("profiles", "0021_alter_profile_newsletter_opt_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="organizers",
            field=models.ManyToManyField(
                blank=True, related_name="organized_districts", to="profiles.profile"
            ),
        ),
    ]
