# Generated by Django 5.1.15 on 2026-02-16 21:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facets", "0006_ward"),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("mpoly", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("properties", models.JSONField()),
                ("targetable", models.BooleanField(default=False)),
                (
                    "ward",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="facets.ward",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
