# Generated by Django 5.1.15 on 2026-02-16 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facets", "0007_division"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={
                "verbose_name": "Political Division",
                "verbose_name_plural": "Political Divisions",
            },
        ),
        migrations.AlterModelOptions(
            name="ward",
            options={"verbose_name": "Political Ward", "verbose_name_plural": "Political Wards"},
        ),
    ]
