# Generated by Django 4.2.13 on 2025-01-14 14:43

import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_cmsstreampage_navigationcontainerpage_delete_cmspage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsstreampage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "Left"),
                                            ("center", "Center"),
                                            ("right", "Right"),
                                        ]
                                    ),
                                ),
                                ("paragraph", wagtail.blocks.RichTextBlock()),
                            ],
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ],
                        ),
                    ),
                    ("html", wagtail.blocks.RawHTMLBlock()),
                    (
                        "table",
                        wagtail.contrib.table_block.blocks.TableBlock(
                            table_options={
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "copy",
                                    "cut",
                                    "---------",
                                    "alignment",
                                ],
                                "editor": "text",
                                "renderer": "html",
                            }
                        ),
                    ),
                ]
            ),
        ),
    ]
