# Generated by Django 4.2.11 on 2024-05-29 14:51

import uuid

import django.db.models.deletion
import markdownfield.models
from django.db import migrations, models

import pbaabp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                ("title", models.CharField(max_length=512)),
                ("release", pbaabp.models.MarkdownField(rendered_field="release_rendered")),
                ("release_rendered", markdownfield.models.RenderedMarkdownField()),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nickname", models.CharField(max_length=64)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="release.release",
                    ),
                ),
            ],
        ),
    ]
