# Generated by Django 4.2.9 on 2024-03-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighborhood_selection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighborhood",
            name="requests",
            field=models.IntegerField(default=0),
        ),
    ]
