# Generated by Django 4.2.11 on 2024-05-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighborhood_selection", "0002_neighborhood_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighborhood",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
