# Generated by Django 4.2.13 on 2024-11-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facets", "0004_statehousedistrict_statesenatedistrict"),
        ("neighborhood_selection", "0003_neighborhood_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighborhood",
            name="rcos",
            field=models.ManyToManyField(to="facets.registeredcommunityorganization"),
        ),
    ]
