# Generated by Django 4.2.9 on 2024-03-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
