# Generated by Django 4.2.9 on 2024-03-25 18:17

import django.utils.timezone
from django.db import migrations, models

import pbaabp.models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0004_petition_petitionsignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="email_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="petition",
            name="email_include_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="petition",
            name="email_subject",
            field=models.CharField(blank=True, max_length=988, null=True),
        ),
        migrations.AddField(
            model_name="petitionsignature",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="petitionsignature",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="petitionsignature",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="petition",
            name="signature_fields",
            field=pbaabp.models.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("first_name", "First Name"),
                        ("last_name", "Last Name"),
                        ("email", "E-mail"),
                        ("postal_address_line_1", "Address Line 1"),
                        ("postal_address_line_2", "Address Line 2"),
                        ("city", "City"),
                        ("state", "State"),
                        ("zip_code", "Zip Code"),
                        ("comment", "Comment"),
                    ],
                    max_length=128,
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
