# Generated by Django 4.2.9 on 2024-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0007_petition_call_to_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="campaigns"),
        ),
    ]
