# Generated by Django 4.2.11 on 2024-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0008_alter_campaign_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionsignature",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
