# Generated by Django 4.2.11 on 2024-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0009_petitionsignature_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="signature_goal",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
