# Generated by Django 4.2.11 on 2024-05-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0010_petition_signature_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("suspended", "Suspended"),
                    ("unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
    ]
