# Generated by Django 4.2.11 on 2024-05-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0011_alter_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="donation_action",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="subscription_action",
            field=models.BooleanField(default=False),
        ),
    ]
