# Generated by Django 4.2.13 on 2024-07-18 14:41

import django.core.validators
from django.db import migrations, models

import pbaabp.models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0012_campaign_donation_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="call_to_action",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="petition",
            name="display_on_campaign_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="petition",
            name="mailto_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="petitionsignature",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message=(
                            "Phone number must be entered in the format: "
                            "'+999999999'. Up to 15 digits allowed."
                        ),
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="signature_fields",
            field=pbaabp.models.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("first_name", "First Name"),
                        ("last_name", "Last Name"),
                        ("email", "E-mail"),
                        ("phone_number", "Phone Number"),
                        ("postal_address_line_1", "Address Line 1"),
                        ("postal_address_line_2", "Address Line 2"),
                        ("city", "City"),
                        ("state", "State"),
                        ("zip_code", "Zip Code"),
                        ("comment", "Comment"),
                    ],
                    max_length=128,
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
