# Generated by Django 4.2.13 on 2024-07-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0014_alter_campaign_options_campaign_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionsignature",
            name="newsletter_opt_in",
            field=models.BooleanField(default=True, verbose_name="Newsletter Opt-In"),
        ),
    ]
