# Generated by Django 4.2.13 on 2024-11-22 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_donation"),
        ("campaigns", "0016_campaign_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="donation_goal",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="donation_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="membership.donationproduct",
            ),
        ),
    ]
