# Generated by Django 4.2.13 on 2024-11-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0017_campaign_donation_goal_campaign_donation_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="call_to_action_header",
            field=models.BooleanField(default=True),
        ),
    ]
