# Generated by Django 4.2.18 on 2025-03-10 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0019_campaign_donation_goal_show_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionsignature",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
