# Generated by Django 5.1.15 on 2026-01-18 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0029_petition_post_sign_email_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionsignature",
            name="checkbox_responses",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="PetitionCheckbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("label", models.CharField(max_length=512)),
                ("help_text", models.CharField(blank=True, default="", max_length=1024)),
                ("required", models.BooleanField(default=False)),
                (
                    "petition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkboxes",
                        to="campaigns.petition",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
